#import "./group.gql"

fragment GroupInviteBase on GroupInvite {
  id
  kind
  status
  role
  observer
  expiresAt
  createdAt
  group {
    id
    name
  }
  invitedBy {
    id
    name
    username
  }
}
