#import "./profileHeader.gql"
#import "./trickBox.gql"
#import "./speedPersonalBest.gql"
#import "./speedAnalysis.gql"

fragment ProfileUser on User {
  ...ProfileHeader
  speedBests @include(if: $withSpeed) {
    ...SpeedPersonalBestBase
    total {
      analysis {
        ...SpeedAnalysisFields
      }
    }
    ownSegment {
      result {
        analysis {
          ...SpeedAnalysisFields
        }
      }
    }
  }
  checklist @include(if: $withChecklist) {
    id
    trick {
      ...TrickBox
    }
  }
}
