#import "./speedSegment.gql"

fragment SpeedAnalysisFields on SpeedAnalysis {
  duration
  stepsPerSecond
  maxStepsPerSecond
  misses
  stepsLost
  stepsPerSecondSeries
  segments {
    ...SpeedSegmentFields
  }
}
