fragment SpeedAnalysisFields on SpeedAnalysis {
  duration
  stepsPerSecond
  maxStepsPerSecond
  misses
  stepsLost
  stepsPerSecondSeries
  segments {
    index
    label
    start
    end
    count
    stepsPerSecond
  }
}
