fragment TrickBox on Trick {
  id
  slug
  discipline
  tags {
    tag {
      id
      slug
    }
    number
    values {
      id
    }
  }
  en: localisation {
    id
    name
  }
  localised: localisation (lang: $lang) @include(if: $withLocalised) {
    id
    name
  }
  ttLevels: levels (rulesId: "tricktionary") {
    id
    level
  }
}
