fragment TrickSubmissionBase on TrickSubmission {
  id
  kind
  name
  discipline
  status
  reviewNote
  createdAt
  upload {
    id
    status
    error
  }
  trick {
    id
    slug
    discipline
  }
}
