#import "../fragments/speedResult.gql"

query GroupSpeedResults ($groupId: ID!, $limit: Int, $startAfter: Timestamp, $eventDefinitionId: ID, $constellation: [ID!]) {
  group (groupId: $groupId) {
    id
    speedResults (limit: $limit, startAfter: $startAfter, eventDefinitionId: $eventDefinitionId, constellation: $constellation) {
      ...SpeedResultBase
    }
  }
}

query GroupConstellations ($groupId: ID!) {
  group (groupId: $groupId) {
    id
    constellations {
      key
      resultCount
      members {
        id
        name
      }
    }
  }
}

query GroupMemberSpeed ($memberId: ID!, $eventDefinitionId: ID!, $withProgression: Boolean!) {
  groupMember (memberId: $memberId) {
    id
    speedPersonalBests {
      ...SpeedResultBase
    }
    speedProgression (eventDefinitionId: $eventDefinitionId) @include(if: $withProgression) {
      count
      stepsPerSecond
      segment {
        index
        label
      }
      result {
        id
        createdAt
        participants {
          ...SpeedParticipantBase
        }
      }
    }
  }
}
