query Me ($withChecklist: Boolean!) {
  me {
    id
    username
    name
    photo
    email
    lang
    theme
    profile {
      public
      checklist
      speed
    }
    checklist @include(if: $withChecklist) {
      id
      createdAt
      trick {
        id
      }
      recordedBy {
        id
        name
      }
    }
  }
}
