query SpeedResult ($speedResultId: ID!) {
  me {
    id
    speedResult (speedResultId: $speedResultId) {
      ...SpeedResultBase
      ...SpeedResultSharing
      analysis {
        ...SpeedAnalysisFields
      }
    }
  }
}
