query SpeedResults ($limit: Int, $startAfter: Timestamp, $eventDefinitionId: ID) {
  me {
    id
    speedResults (limit: $limit, startAfter: $startAfter, eventDefinitionId: $eventDefinitionId) {
      ...SpeedResultBase
    }
  }
}
