query SpeedResult ($speedResultId: ID!) {
  me {
    id
    speedResult (speedResultId: $speedResultId) {
      ...SpeedResultBase
      analysis {
        duration
        stepsPerSecond
        maxStepsPerSecond
        misses
        stepsLost
        stepsPerSecondSeries
      }
    }
  }
}
