#import "../fragments/trickBox.gql"

query TrickBySlug ($discipline: Discipline!, $slug: String!, $withLocalised: Boolean!, $lang: String) {
  trick: trickBySlug (discipline: $discipline, slug: $slug) {
    ...TrickBox
    en: localisation {
      id
      name
      alternativeNames
      description
    }
    localised: localisation (lang: $lang) @include(if: $withLocalised) {
      id
      name
      alternativeNames
      description
    }
    videos {
      videoId
      type
      host
    }
    levels {
      id
      rulesId
      level
      verificationLevel
      ruleset {
        id
        name (lang: $lang)
        isPrimary
      }
    }
    prerequisites {
      ...TrickBox
    }
    prerequisiteFor {
      ...TrickBox
    }
  }
}
